/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.rs"],
  theme: {
    extend: {
      colors: {
        "bg":               "var(--bg)",
        "bg-elev-1":        "var(--bg-elev-1)",
        "bg-elev-2":        "var(--bg-elev-2)",
        "bg-elev-3":        "var(--bg-elev-3)",
        "bg-input":         "var(--bg-input)",
        "bg-input-deep":    "var(--bg-input-deep)",
        "bg-panel":         "var(--bg-panel)",
        "bg-panel-dim":     "var(--bg-panel-dim)",
        "bg-panel-glass":   "var(--bg-panel-glass)",
        "bg-panel-solid":   "var(--bg-panel-solid)",
        "bg-section-hdr":   "var(--bg-section-hdr)",
        "bg-button":        "var(--bg-button)",
        "bg-button-info":   "var(--bg-button-info)",
        "bg-button-ok":     "var(--bg-button-ok)",
        "bg-banner":        "var(--bg-banner)",
        "bg-wheel":         "var(--bg-wheel)",
        "glass-bg":         "var(--glass-bg)",
        "glass-bg-strong":  "var(--glass-bg-strong)",
        "glass-border":     "var(--glass-border)",
        "text":             "var(--text)",
        "text-dim":         "var(--text-dim)",
        "text-muted":       "var(--text-muted)",
        "text-faint":       "var(--text-faint)",
        "text-blue":        "var(--text-blue)",
        "text-blue-bright": "var(--text-blue-bright)",
        "accent-cyan":        "var(--accent-cyan)",
        "accent-cyan-dim":    "var(--accent-cyan-dim)",
        "accent-violet":      "var(--accent-violet)",
        "accent-amber":       "var(--accent-amber)",
        "accent-green":       "var(--accent-green)",
        "accent-green-soft":  "var(--accent-green-soft)",
        "accent-blue-active": "var(--accent-blue-active)",
        "state-ok":         "var(--state-ok)",
        "state-warn":       "var(--state-warn)",
        "state-err":        "var(--state-err)",
        "state-info":       "var(--state-info)",
        "border-base":      "var(--border)",
        "border-strong":    "var(--border-strong)",
        "border-mid":       "var(--border-mid)",
        "border-input":     "var(--border-input)",
        "border-accent":    "var(--border-accent)",
        "border-accent-2":  "var(--border-accent-2)",
        "border-ok":        "var(--border-ok)",
        "border-info":      "var(--border-info)",
      },
      spacing: {
        "sp-0": "var(--sp-0)",
        "sp-1": "var(--sp-1)",
        "sp-2": "var(--sp-2)",
        "sp-3": "var(--sp-3)",
        "sp-4": "var(--sp-4)",
        "sp-5": "var(--sp-5)",
        "sp-6": "var(--sp-6)",
        "sp-7": "var(--sp-7)",
      },
      borderRadius: {
        "sm":   "var(--r-sm)",
        "md":   "var(--r-md)",
        "lg":   "var(--r-lg)",
        "xl":   "var(--r-xl)",
        "pill": "var(--r-pill)",
      },
      fontFamily: {
        "ui":   ["var(--font-ui)"],
        "mono": ["var(--font-mono)"],
      },
      fontSize: {
        "xs":   "var(--fs-xs)",
        "sm":   "var(--fs-sm)",
        "md":   "var(--fs-md)",
        "base": "var(--fs-base)",
        "lg":   "var(--fs-lg)",
        "xl":   "var(--fs-xl)",
        "2xl":  "var(--fs-2xl)",
      },
      boxShadow: {
        "1": "var(--shadow-1)",
        "2": "var(--shadow-2)",
        "3": "var(--shadow-3)",
        "ring": "var(--ring)",
      },
      transitionDuration: {
        "fast": "var(--dur-fast)",
        "base": "var(--dur-base)",
        "slow": "var(--dur-slow)",
      },
      transitionTimingFunction: {
        "out":    "var(--ease-out)",
        "spring": "var(--ease-spring)",
      },
      backdropBlur: {
        "glass": "14px",
      },
    },
  },
  plugins: [],
};
