//! Deep-sky object catalog — loaded at runtime from `/dso.bin`.
//!
//! Binary format (little-endian):
//!   [u32] n_objects
//!   Objects: ra_deg(f32), dec_deg(f32), mag(f32), size_arcmin(f32),
//!            size_minor_arcmin(f32), pa_deg(f32), kind(u8),
//!            name_len(u8), name(utf8),
//!            aliases_count(u8),
//!            [ alias_len(u8), alias(utf8) ] × aliases_count,
//!            fr_names_count(u8),
//!            [ fr_name_len(u8), fr_name(utf8) ] × fr_names_count,
//!            ids_count(u8),
//!            [ id_len(u8), id(utf8) ] × ids_count
//!
//! kind codes: 0=Galaxy 1=OpenCluster 2=GlobularCluster 3=Nebula
//!             4=PlanetaryNebula 5=SupernovaRemnant 6=GalaxyCluster
//!             7=DarkNebula
//!
//! Auto-generated by scripts/gen_dso_catalog.py — do not edit by hand.

use std::sync::Arc;

use crate::i18n::Lang;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum DsoType {
    Galaxy,
    OpenCluster,
    GlobularCluster,
    Nebula,
    PlanetaryNebula,
    SupernovaRemnant,
    GalaxyCluster,
    DarkNebula,
}

pub struct Dso {
    pub ra_deg: f32,
    pub dec_deg: f32,
    /// Visual magnitude (99.0 = unknown)
    pub mag: f32,
    /// Magnitude the sky culls by: `mag` when the catalog has one, else a
    /// stand-in from the apparent size. Most nebulae, dark clouds and clusters
    /// outside the NGC have no magnitude and would otherwise never pass the
    /// slider. 15 − 2.5·log10(size′): with the zoom-driven limit a 2°
    /// Sharpless region shows from a ~25° field, a 10′ one from ~3°.
    pub vis_mag: f32,
    /// Major axis in arcminutes
    pub size_arcmin: f32,
    /// Minor axis in arcminutes (0 = unknown / circular)
    pub size_minor_arcmin: f32,
    /// Position angle in degrees (0 = N, 90 = E)
    pub pa_deg: f32,
    pub kind: DsoType,
    pub name: String,
    /// Human-readable aliases from OpenNGC's "Common names" column
    /// (e.g. `["Andromeda Galaxy"]` for M31). Empty when none are known.
    pub common_names: Vec<String>,
    /// French-language aliases pulled from Wikidata at catalog-generation
    /// time (e.g. `["Galaxie d'Andromède"]` for M31). Searched alongside
    /// `common_names` so French queries resolve.
    pub fr_names: Vec<String>,
    /// Other designations of the same object (`["Sh2-117", "Caldwell 20",
    /// "LBN 373"]` for NGC 7000): searched, never displayed.
    pub ids: Vec<String>,
}

impl Dso {
    /// The catalog magnitude, `None` when unknown.
    pub fn known_mag(&self) -> Option<f32> {
        (self.mag < 90.0).then_some(self.mag)
    }

    /// "M31 · Andromeda Galaxy" (EN) or "M31 · galaxie d'Andromède" (FR).
    /// Used for on-canvas labels, hit-item titles, and search results so they
    /// all agree on a single display form. Falls back to the cross-locale
    /// alias when the locale-preferred list is empty, then to the bare
    /// designation when no aliases exist at all.
    pub fn display_label(&self, lang: Lang) -> String {
        let preferred = match lang {
            Lang::Fr => self.fr_names.first().or_else(|| self.common_names.first()),
            Lang::En => self.common_names.first().or_else(|| self.fr_names.first()),
        };
        match preferred {
            Some(c) => format!("{} · {}", self.name, c),
            None    => self.name.clone(),
        }
    }
}

pub struct DsoCatalogData {
    pub dsos: Vec<Dso>,
}

impl DsoCatalogData {
    pub fn parse(data: &[u8]) -> Option<Self> {
        let mut pos = 0usize;
        let n = rd_u32(data, &mut pos)? as usize;
        let mut dsos = Vec::with_capacity(n);
        for _ in 0..n {
            let ra_deg            = rd_f32(data, &mut pos)?;
            let dec_deg           = rd_f32(data, &mut pos)?;
            let mag               = rd_f32(data, &mut pos)?;
            let size_arcmin       = rd_f32(data, &mut pos)?;
            let size_minor_arcmin = rd_f32(data, &mut pos)?;
            let pa_deg            = rd_f32(data, &mut pos)?;
            let kind_byte = *data.get(pos)?; pos += 1;
            let kind = match kind_byte {
                0 => DsoType::Galaxy,
                1 => DsoType::OpenCluster,
                2 => DsoType::GlobularCluster,
                3 => DsoType::Nebula,
                4 => DsoType::PlanetaryNebula,
                5 => DsoType::SupernovaRemnant,
                6 => DsoType::GalaxyCluster,
                7 => DsoType::DarkNebula,
                _ => DsoType::Galaxy,
            };
            let name = rd_str(data, &mut pos)?;
            let common_names = rd_str_list(data, &mut pos)?;
            let fr_names = rd_str_list(data, &mut pos)?;
            let ids = rd_str_list(data, &mut pos)?;
            let vis_mag = if mag < 90.0 {
                mag
            } else if size_arcmin > 0.0 {
                (15.0 - 2.5 * size_arcmin.log10()).clamp(4.0, 16.0)
            } else {
                16.0
            };
            dsos.push(Dso {
                ra_deg, dec_deg, mag, vis_mag, size_arcmin, size_minor_arcmin, pa_deg, kind,
                name, common_names, fr_names, ids,
            });
        }
        Some(DsoCatalogData { dsos })
    }
}

/// Bump `v` with every change to the binary layout: the file is served
/// without cache headers, and a browser holding the previous `dso.bin` would
/// otherwise feed it to this parser.
pub async fn fetch_dso_catalog() -> Option<Arc<DsoCatalogData>> {
    let bytes = gloo_net::http::Request::get("/dso.bin?v=2")
        .send().await.ok()?
        .binary().await.ok()?;
    DsoCatalogData::parse(&bytes).map(Arc::new)
}

// ── Binary helpers ───────────────────────────────────────────────────────────

fn rd_u32(data: &[u8], pos: &mut usize) -> Option<u32> {
    let end = pos.checked_add(4)?;
    let v = u32::from_le_bytes(data.get(*pos..end)?.try_into().ok()?);
    *pos = end;
    Some(v)
}

fn rd_f32(data: &[u8], pos: &mut usize) -> Option<f32> {
    let end = pos.checked_add(4)?;
    let v = f32::from_le_bytes(data.get(*pos..end)?.try_into().ok()?);
    *pos = end;
    Some(v)
}

/// A count-prefixed list of strings.
fn rd_str_list(data: &[u8], pos: &mut usize) -> Option<Vec<String>> {
    let count = *data.get(*pos)?;
    *pos += 1;
    (0..count).map(|_| rd_str(data, pos)).collect()
}

fn rd_str(data: &[u8], pos: &mut usize) -> Option<String> {
    let len = *data.get(*pos)? as usize;
    *pos += 1;
    let end = pos.checked_add(len)?;
    let s = std::str::from_utf8(data.get(*pos..end)?).ok()?.to_string();
    *pos = end;
    Some(s)
}
