//! Runtime nebulae texture index — loaded from `/nebulae.json` at startup.
//!
//! The JSON is generated by `scripts/download_nebulae.py` and served statically.
//! It is never compiled into the WASM binary.

use std::collections::HashMap;
use std::sync::Arc;

use serde::Deserialize;

/// One nebula texture entry deserialized from `/nebulae.json`.
#[derive(Deserialize, Clone)]
pub struct NebulaTex {
    /// Catalog name matching dso.bin format (e.g. "M31", "NGC 1023", "IC 434")
    pub name: String,
    /// URL path served from web root (e.g. "nebulae/m42.png")
    pub path: String,
    /// Sky corners (ra_deg, dec_deg) J2000: BL, BR, TR, TL
    pub corners: [(f32, f32); 4],
}

/// Index of all nebula textures keyed by catalog name.
pub struct NebulaeIndex {
    pub map: HashMap<String, NebulaTex>,
}

impl NebulaeIndex {
    pub fn from_json(json: &str) -> Option<Arc<Self>> {
        let list: Vec<NebulaTex> = serde_json::from_str(json).ok()?;
        let map = list.into_iter().map(|t| (t.name.clone(), t)).collect();
        Some(Arc::new(NebulaeIndex { map }))
    }
}

/// Fetch `/nebulae.json` and parse it.
pub async fn fetch_nebulae_index() -> Option<Arc<NebulaeIndex>> {
    let text = gloo_net::http::Request::get("/nebulae.json")
        .send().await.ok()?
        .text().await.ok()?;
    NebulaeIndex::from_json(&text)
}
