//! Deep star layer — Tycho-2 beyond `junos.bin`, loaded at runtime from
//! `/tycho.bin`, only once the sky is zoomed in past `junos.bin`'s depth.
//!
//! Binary format (little-endian), written by `scripts/gen_star_tiles.py`:
//!   "TYC2", [u32] n_bands, [u32] n_tiles,
//!   [f32] band_deg, [f32] mag0, [f32] mag_step, [f32] bv_step,
//!   [u32] × n_bands   RA cells per declination band, from the south pole up
//!   [u32] × n_tiles   stars per tile (band-major, RA-minor)
//!   then the stars, tile after tile, brightest first, 6 bytes each:
//!   ra(u16) dec(u16) — position across the tile, in 1/65536ths —
//!   mag(u8) = (V − mag0) / mag_step, bv(i8) = (B−V) / bv_step
//!
//! Auto-generated by scripts/gen_star_tiles.py — do not edit by hand.

use std::sync::Arc;

const STAR_BYTES: usize = 6;

pub struct DeepStarCatalog {
    data: Vec<u8>,
    band_deg: f32,
    mag0: f32,
    mag_step: f32,
    bv_step: f32,
    /// RA cells in each band.
    band_cells: Vec<u32>,
    /// Index of each band's first tile; one extra entry at the end.
    band_first_tile: Vec<u32>,
    /// Index of each tile's first star; one extra entry at the end.
    tile_first_star: Vec<u32>,
    /// Byte offset of the first star record.
    stars_at: usize,
}

impl DeepStarCatalog {
    pub fn parse(data: Vec<u8>) -> Option<Self> {
        if data.get(0..4)? != b"TYC2" {
            return None;
        }
        let mut pos = 4;
        let n_bands = rd_u32(&data, &mut pos)? as usize;
        let n_tiles = rd_u32(&data, &mut pos)? as usize;
        let band_deg = rd_f32(&data, &mut pos)?;
        let mag0 = rd_f32(&data, &mut pos)?;
        let mag_step = rd_f32(&data, &mut pos)?;
        let bv_step = rd_f32(&data, &mut pos)?;

        let mut band_cells = Vec::with_capacity(n_bands);
        let mut band_first_tile = vec![0u32];
        for _ in 0..n_bands {
            let n = rd_u32(&data, &mut pos)?.max(1);
            band_cells.push(n);
            band_first_tile.push(band_first_tile.last()? + n);
        }
        if *band_first_tile.last()? as usize != n_tiles {
            return None;
        }

        let mut tile_first_star = vec![0u32];
        for _ in 0..n_tiles {
            let n = rd_u32(&data, &mut pos)?;
            tile_first_star.push(tile_first_star.last()? + n);
        }
        let stars_at = pos;
        if stars_at + *tile_first_star.last()? as usize * STAR_BYTES != data.len() {
            return None;
        }

        Some(Self {
            data, band_deg, mag0, mag_step, bv_step,
            band_cells, band_first_tile, tile_first_star, stars_at,
        })
    }

    /// Every tile that may hold a star within `radius_deg` of (ra, dec), J2000.
    /// Conservative: a band takes the cap's widest RA extent.
    pub fn tiles_in_cap(&self, ra_deg: f64, dec_deg: f64, radius_deg: f64, out: &mut Vec<u32>) {
        out.clear();
        let band_deg = self.band_deg as f64;
        let n_bands = self.band_cells.len();
        let lo = ((dec_deg - radius_deg + 90.0) / band_deg).floor().max(0.0) as usize;
        let hi = (((dec_deg + radius_deg + 90.0) / band_deg).floor() as usize).min(n_bands - 1);
        // RA half-width of the cap; a cap over a pole spans every RA.
        let half_ra = if dec_deg.abs() + radius_deg >= 89.9 {
            180.0
        } else {
            (radius_deg.to_radians().sin() / dec_deg.to_radians().cos())
                .min(1.0)
                .asin()
                .to_degrees()
        };
        for band in lo..=hi {
            let n = self.band_cells[band];
            let first = self.band_first_tile[band];
            if half_ra >= 180.0 {
                out.extend(first..first + n);
                continue;
            }
            let width = 360.0 / n as f64;
            let c0 = ((ra_deg - half_ra) / width).floor() as i64;
            let c1 = ((ra_deg + half_ra) / width).floor() as i64;
            for c in c0..=c1.min(c0 + n as i64 - 1) {
                out.push(first + c.rem_euclid(n as i64) as u32);
            }
        }
    }

    /// Append the stars of `tile` as `[ra_deg, dec_deg, mag, bv]` (the
    /// `CatalogData::packed_star_buffer` layout), brightest first.
    pub fn decode_tile(&self, tile: u32, out: &mut Vec<[f32; 4]>) {
        let t = tile as usize;
        let (Some(&first), Some(&end)) = (self.tile_first_star.get(t), self.tile_first_star.get(t + 1))
        else { return };
        // The band a tile belongs to: the last band starting at or before it.
        let band = self.band_first_tile.partition_point(|&f| f <= tile) - 1;
        let n = self.band_cells[band];
        let width = 360.0 / n as f32;
        let ra_lo = (tile - self.band_first_tile[band]) as f32 * width;
        let dec_lo = -90.0 + band as f32 * self.band_deg;
        let bytes = &self.data[self.stars_at + first as usize * STAR_BYTES..self.stars_at + end as usize * STAR_BYTES];
        out.reserve(bytes.len() / STAR_BYTES);
        for s in bytes.chunks_exact(STAR_BYTES) {
            let qra = u16::from_le_bytes([s[0], s[1]]) as f32;
            let qdec = u16::from_le_bytes([s[2], s[3]]) as f32;
            out.push([
                ra_lo + (qra + 0.5) / 65536.0 * width,
                dec_lo + (qdec + 0.5) / 65536.0 * self.band_deg,
                self.mag0 + s[4] as f32 * self.mag_step,
                s[5] as i8 as f32 * self.bv_step,
            ]);
        }
    }
}

pub async fn fetch_deep_stars() -> Option<Arc<DeepStarCatalog>> {
    let bytes = gloo_net::http::Request::get("/tycho.bin")
        .send().await.ok()?
        .binary().await.ok()?;
    DeepStarCatalog::parse(bytes).map(Arc::new)
}

fn rd_u32(data: &[u8], pos: &mut usize) -> Option<u32> {
    let end = pos.checked_add(4)?;
    let v = u32::from_le_bytes(data.get(*pos..end)?.try_into().ok()?);
    *pos = end;
    Some(v)
}

fn rd_f32(data: &[u8], pos: &mut usize) -> Option<f32> {
    let end = pos.checked_add(4)?;
    let v = f32::from_le_bytes(data.get(*pos..end)?.try_into().ok()?);
    *pos = end;
    Some(v)
}
