/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.rs"],
  theme: {
    extend: {
      colors: {
        "bg":               "var(--bg)",
        "bg-input":         "var(--bg-input)",
        "bg-input-deep":    "var(--bg-input-deep)",
        "bg-panel":         "var(--bg-panel)",
        "bg-panel-dim":     "var(--bg-panel-dim)",
        "bg-panel-glass":   "var(--bg-panel-glass)",
        "bg-panel-solid":   "var(--bg-panel-solid)",
        "bg-section-hdr":   "var(--bg-section-hdr)",
        "bg-button":        "var(--bg-button)",
        "bg-button-info":   "var(--bg-button-info)",
        "bg-button-ok":     "var(--bg-button-ok)",
        "bg-banner":        "var(--bg-banner)",
        "bg-wheel":         "var(--bg-wheel)",
        "text-dim":         "var(--text-dim)",
        "text-muted":       "var(--text-muted)",
        "text-faint":       "var(--text-faint)",
        "text-blue":        "var(--text-blue)",
        "text-blue-bright": "var(--text-blue-bright)",
        "accent-cyan":        "var(--accent-cyan)",
        "accent-cyan-dim":    "var(--accent-cyan-dim)",
        "accent-amber":       "var(--accent-amber)",
        "accent-green":       "var(--accent-green)",
        "accent-green-soft":  "var(--accent-green-soft)",
        "accent-blue-active": "var(--accent-blue-active)",
        "border-base":      "var(--border)",
        "border-strong":    "var(--border-strong)",
        "border-mid":       "var(--border-mid)",
        "border-input":     "var(--border-input)",
        "border-accent":    "var(--border-accent)",
        "border-accent-2":  "var(--border-accent-2)",
        "border-ok":        "var(--border-ok)",
        "border-info":      "var(--border-info)",
      },
      spacing: {
        "sp-1": "var(--sp-1)",
        "sp-2": "var(--sp-2)",
        "sp-3": "var(--sp-3)",
        "sp-4": "var(--sp-4)",
        "sp-5": "var(--sp-5)",
      },
      borderRadius: {
        "sm": "var(--r-sm)",
        "md": "var(--r-md)",
        "lg": "var(--r-lg)",
      },
      fontFamily: {
        "mono": ["var(--font-mono)"],
      },
      fontSize: {
        "xs":   "var(--fs-xs)",
        "sm":   "var(--fs-sm)",
        "md":   "var(--fs-md)",
        "base": "var(--fs-base)",
        "lg":   "var(--fs-lg)",
      },
    },
  },
  plugins: [],
};
