//! Deep-sky object catalog — loaded at runtime from `/dso.bin`.
//!
//! Binary format (little-endian):
//!   [u32] n_objects
//!   Objects: ra_deg(f32), dec_deg(f32), mag(f32), size_arcmin(f32),
//!            size_minor_arcmin(f32), pa_deg(f32), kind(u8),
//!            name_len(u8), name(utf8),
//!            aliases_count(u8),
//!            [ alias_len(u8), alias(utf8) ] × aliases_count
//!
//! kind codes: 0=Galaxy 1=OpenCluster 2=GlobularCluster 3=Nebula
//!             4=PlanetaryNebula 5=SupernovaRemnant 6=GalaxyCluster
//!
//! Auto-generated by scripts/gen_dso_catalog.py — do not edit by hand.

use std::sync::Arc;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum DsoType {
    Galaxy,
    OpenCluster,
    GlobularCluster,
    Nebula,
    PlanetaryNebula,
    SupernovaRemnant,
    GalaxyCluster,
}

pub struct Dso {
    pub ra_deg: f32,
    pub dec_deg: f32,
    /// Visual magnitude (99.0 = unknown)
    pub mag: f32,
    /// Major axis in arcminutes
    pub size_arcmin: f32,
    /// Minor axis in arcminutes (0 = unknown / circular)
    pub size_minor_arcmin: f32,
    /// Position angle in degrees (0 = N, 90 = E)
    pub pa_deg: f32,
    pub kind: DsoType,
    pub name: String,
    /// Human-readable aliases from OpenNGC's "Common names" column
    /// (e.g. `["Andromeda Galaxy"]` for M31). Empty when none are known.
    pub common_names: Vec<String>,
}

impl Dso {
    /// "M31 · Andromeda Galaxy" when a common name exists, "M31" otherwise.
    /// Used for on-canvas labels, hit-item titles, and search results so they
    /// all agree on a single display form.
    pub fn display_label(&self) -> String {
        match self.common_names.first() {
            Some(c) => format!("{} · {}", self.name, c),
            None    => self.name.clone(),
        }
    }
}

pub struct DsoCatalogData {
    pub dsos: Vec<Dso>,
}

impl DsoCatalogData {
    pub fn parse(data: &[u8]) -> Option<Self> {
        let mut pos = 0usize;
        let n = rd_u32(data, &mut pos)? as usize;
        let mut dsos = Vec::with_capacity(n);
        for _ in 0..n {
            let ra_deg            = rd_f32(data, &mut pos)?;
            let dec_deg           = rd_f32(data, &mut pos)?;
            let mag               = rd_f32(data, &mut pos)?;
            let size_arcmin       = rd_f32(data, &mut pos)?;
            let size_minor_arcmin = rd_f32(data, &mut pos)?;
            let pa_deg            = rd_f32(data, &mut pos)?;
            let kind_byte = *data.get(pos)?; pos += 1;
            let kind = match kind_byte {
                0 => DsoType::Galaxy,
                1 => DsoType::OpenCluster,
                2 => DsoType::GlobularCluster,
                3 => DsoType::Nebula,
                4 => DsoType::PlanetaryNebula,
                5 => DsoType::SupernovaRemnant,
                6 => DsoType::GalaxyCluster,
                _ => DsoType::Galaxy,
            };
            let name = rd_str(data, &mut pos)?;
            let aliases_count = *data.get(pos)? as usize; pos += 1;
            let mut common_names = Vec::with_capacity(aliases_count);
            for _ in 0..aliases_count {
                common_names.push(rd_str(data, &mut pos)?);
            }
            dsos.push(Dso { ra_deg, dec_deg, mag, size_arcmin, size_minor_arcmin, pa_deg, kind, name, common_names });
        }
        Some(DsoCatalogData { dsos })
    }
}

pub async fn fetch_dso_catalog() -> Option<Arc<DsoCatalogData>> {
    let bytes = gloo_net::http::Request::get("/dso.bin")
        .send().await.ok()?
        .binary().await.ok()?;
    DsoCatalogData::parse(&bytes).map(Arc::new)
}

// ── Binary helpers ───────────────────────────────────────────────────────────

fn rd_u32(data: &[u8], pos: &mut usize) -> Option<u32> {
    let end = pos.checked_add(4)?;
    let v = u32::from_le_bytes(data.get(*pos..end)?.try_into().ok()?);
    *pos = end;
    Some(v)
}

fn rd_f32(data: &[u8], pos: &mut usize) -> Option<f32> {
    let end = pos.checked_add(4)?;
    let v = f32::from_le_bytes(data.get(*pos..end)?.try_into().ok()?);
    *pos = end;
    Some(v)
}

fn rd_str(data: &[u8], pos: &mut usize) -> Option<String> {
    let len = *data.get(*pos)? as usize;
    *pos += 1;
    let end = pos.checked_add(len)?;
    let s = std::str::from_utf8(data.get(*pos..end)?).ok()?.to_string();
    *pos = end;
    Some(s)
}
